** which-key in the Sky with Diamonds
vertico.el lets you easily see which keybindings are associated to
commands. This information was anyway available:

- while completing commands with =TAB=.
- asking Emacs for command's documentation with =M-x describe-command
  RET <command> RET=.

You will eventually end up learning:

| Command                      | Action      | Keybinding |
|------------------------------+-------------+------------|
| =find-file=                  | Open a file | =C-x C-f=  |
| =save-buffer=                | Save a file | =C-x C-s=  |
| =save-buffers-kill-terminal= | Quit Emacs  | =C-x C-k=  |

But don't panic: there is no point trying to remember all of them just
yet. Instead, let Emacs remember them for you.

Try =which-key=, a package that suggests key bindings while you type
them. You already know how to locate and edit the Emacs's =init.el=
file. This time, try editing it with Emacs itself:

| Do                              | Comment                                          |
|---------------------------------+--------------------------------------------------|
| =M-x file-open RET=             | or =C-x C-f=                                     |
| =~/.config/emacs.d/init.el RET= | Your mileage might vary: see [[file:use-package.org][Package In A Bottle]] |


#+begin_src elisp
(require 'package)
(package-initialize)

(use-package vertico
  :ensure t
  :config
  (vertico-mode))

(use-package which-key
  :ensure t
  :config
  (which-key-mode))
#+end_src

Nothing new here. You have just installed another package.

Update Emacs re-evaluating the file (=M-x eval-buffer=). Now, if you
begin typing a key binding, say hitting =C-x=, after a bit Emacs,
seing you undecided, will display a cheat-sheet. Since this is
dynamically generated, this will work with any present and future
keybindings.

If you want to close the cheat-sheet before completing the key
binding, you know what to do: use the global =C-g= to abort the key
binding.

=which-key= is useful if you remember part of a key binding. What if
you don't? You can always use =M-x= and type the command: Emacs will
give you the associated keybinding. For example, you probably already
found out that =Ctrl-Z= is not undo. Depressing. Type =M-x undo= and
discover that the right keybinding is =C-x u= (but you can also type
=C-/=, which is easier).

As it happens with most of the Emacs' packages, [[which-key][which-key]] can be
configured in every aspect. Its thorough documentation is worth to be
read. But you have no need to rush: the girl with kaleidoscope eyes is
infinitely understanding and patient. Take your time and enjoy the ride.


#+LINK: which-key https://github.com/justbur/emacs-which-key
