* windmove on up!
I bet you don't believe me, but Emacs is very powerful even without
extensions and plugins. Only, it looks oldish and not very inviting.
So, keep on modernizing it. In the meanwhile, you will discover its
functionalities, one after the other.

Your next goals:

- Make Emacs beautiful looking.
- Go with Language Server Protocol for the win!
- Magit! because you heard it's an application killer.

But first, there is an issue to solve with urgency. Emacs has the
habit of popping up pages, and you don't even know how to move from
one to another. There are no tabs!

My recipe:

- Configure =windmove=.
- Install =consult.el=.
- Learn the bare minimum about buffers and windows.

** Moving from one window to another
Add this to your =init.el=:

#+begin_src elisp
(use-package windmove
  :ensure nil
  :bind
  (("S-<up>". 'windmove-up)
   ("S-<down>". 'windmove-down)
   ("S-<left>". 'windmove-left)
   ("S-<right>". 'windmove-right)))
#+end_src

Save the file (=C-x C-s=) and evaluate its content with =M-x
eval-buffer=.

Here are some notes:

| Code          | Meaning                                                |
|---------------+--------------------------------------------------------|
| =:ensure nil= | =windmove= is built-in: no need to download it.        |
| =:bind=       | =:bind= opens a section with key bindings definitions  |
| ="S-<up>"=    | When =Shift + arrow up= is pressed...                  |
| =windmove-up= | ... invoke =windmove-up=.                              |

When you have multiple pages displayed in Emacs, =windmove-up=,
=windmove-down= etc will move the focus in that direction.\\
Oh, yes: pages are called *windows* in Emacs lingo.

Hey! Wait a sec! Isn't =Shift + arrow keys= reserved for selecting
text? It's not! There are way smarter ways to select text! You'll get
to them. But be patient: after all, you don't even know yet how to
copy/paste.

Move on up! You'll soon learn it all!
